# Generated by Django 2.1 on 2019-04-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Book')),
            ],
        ),
    ]
